

set_property PACKAGE_PIN N6 [get_ports {digits[0]}]
set_property PACKAGE_PIN M6 [get_ports {digits[1]}]
set_property PACKAGE_PIN M3 [get_ports {digits[2]}]
set_property PACKAGE_PIN N5 [get_ports {digits[3]}]
set_property PACKAGE_PIN N2 [get_ports {digits[4]}]
set_property PACKAGE_PIN N4 [get_ports {digits[5]}]
set_property PACKAGE_PIN M1 [get_ports {digits[7]}]
set_property PACKAGE_PIN L1 [get_ports {digits[6]}]


set_property IOSTANDARD LVCMOS33 [get_ports {digits[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digits[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segments[0]}]


set_property PACKAGE_PIN L3 [get_ports {segments[7]}]
set_property PACKAGE_PIN N1 [get_ports {segments[6]}]
set_property PACKAGE_PIN L5 [get_ports {segments[5]}]
set_property PACKAGE_PIN L4 [get_ports {segments[4]}]
set_property PACKAGE_PIN K3 [get_ports {segments[3]}]
set_property PACKAGE_PIN M2 [get_ports {segments[2]}]
set_property PACKAGE_PIN L6 [get_ports {segments[1]}]
set_property PACKAGE_PIN M4 [get_ports {segments[0]}]




set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN T8 [get_ports {LED[0]}]
set_property PACKAGE_PIN V9 [get_ports {LED[1]}]
set_property PACKAGE_PIN R8 [get_ports {LED[2]}]
set_property PACKAGE_PIN T6 [get_ports {LED[3]}]
set_property PACKAGE_PIN T5 [get_ports {LED[4]}]
set_property PACKAGE_PIN T4 [get_ports {LED[5]}]
set_property PACKAGE_PIN U7 [get_ports {LED[6]}]
set_property PACKAGE_PIN U6 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports clock_100MHz]
set_property PACKAGE_PIN E3 [get_ports clock_100MHz]




set_property IOSTANDARD LVCMOS33 [get_ports out_clock]
set_property PACKAGE_PIN B13 [get_ports out_clock]


set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports buttonDownRaw]
set_property IOSTANDARD LVCMOS33 [get_ports buttonLeftRaw]
set_property IOSTANDARD LVCMOS33 [get_ports buttonMiddleRaw]
set_property IOSTANDARD LVCMOS33 [get_ports buttonRightRaw]
set_property IOSTANDARD LVCMOS33 [get_ports buttonUpRaw]
set_property PACKAGE_PIN U9 [get_ports {switchesRaw[0]}]
set_property PACKAGE_PIN V5 [get_ports {switchesRaw[7]}]
set_property PACKAGE_PIN V6 [get_ports {switchesRaw[6]}]
set_property PACKAGE_PIN V7 [get_ports {switchesRaw[5]}]
set_property PACKAGE_PIN R5 [get_ports {switchesRaw[4]}]
set_property PACKAGE_PIN R6 [get_ports {switchesRaw[3]}]
set_property PACKAGE_PIN R7 [get_ports {switchesRaw[2]}]
set_property PACKAGE_PIN U8 [get_ports {switchesRaw[1]}]


set_property PACKAGE_PIN V10 [get_ports buttonDownRaw]
set_property PACKAGE_PIN T16 [get_ports buttonLeftRaw]
set_property PACKAGE_PIN E16 [get_ports buttonMiddleRaw]
set_property PACKAGE_PIN R10 [get_ports buttonRightRaw]


set_property PACKAGE_PIN F15 [get_ports buttonUpRaw]


set_property IOSTANDARD LVCMOS33 [get_ports uart_out]
set_property PACKAGE_PIN F14 [get_ports uart_out]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property PACKAGE_PIN P2 [get_ports {LED[15]}]
set_property PACKAGE_PIN R2 [get_ports {LED[14]}]
set_property PACKAGE_PIN U1 [get_ports {LED[13]}]
set_property PACKAGE_PIN P5 [get_ports {LED[12]}]
set_property PACKAGE_PIN R1 [get_ports {LED[11]}]
set_property PACKAGE_PIN V1 [get_ports {LED[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED[9]}]
set_property PACKAGE_PIN V4 [get_ports {LED[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switchesRaw[8]}]
set_property PACKAGE_PIN P4 [get_ports {switchesRaw[15]}]
set_property PACKAGE_PIN P3 [get_ports {switchesRaw[14]}]
set_property PACKAGE_PIN R3 [get_ports {switchesRaw[13]}]
set_property PACKAGE_PIN T1 [get_ports {switchesRaw[12]}]
set_property PACKAGE_PIN T3 [get_ports {switchesRaw[11]}]
set_property PACKAGE_PIN U2 [get_ports {switchesRaw[10]}]
set_property PACKAGE_PIN V2 [get_ports {switchesRaw[9]}]
set_property PACKAGE_PIN U4 [get_ports {switchesRaw[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports usart_in_clock]
set_property IOSTANDARD LVCMOS33 [get_ports usart_in_data]
set_property IOSTANDARD LVCMOS33 [get_ports usart_out_clock]
set_property IOSTANDARD LVCMOS33 [get_ports usart_out_data]
set_property PACKAGE_PIN E17 [get_ports usart_in_data]
set_property PACKAGE_PIN G13 [get_ports usart_out_clock]
set_property PACKAGE_PIN C17 [get_ports usart_out_data]

set_property PACKAGE_PIN P15 [get_ports usart_in_clock]

set_property SLEW FAST [get_ports out_clock]
set_property SLEW FAST [get_ports uart_out]
set_property SLEW FAST [get_ports usart_out_clock]
set_property SLEW FAST [get_ports usart_out_data]
